{% set name = "pylandstats" %}
{% set version = "3.0.0" %}
{% set sha256 = "503a7c57e335e9d811d8b99985f881f0ae8702600a514f19640a2ed74bd7d5b6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - clang  # [win]
    - clangxx  # [win]
  host:
    - python
    - meson-python
    - numpy >=2.0.2
    - pythran >=0.16.1
    - transonic >=0.4.0
    - pip
  run:
    - python
    - black
    - dask-core
    - geopandas
    - matplotlib-base >=2.2
    - numpy >=1.15
    - pandas >=0.23
    - rasterio >=1.0.0
    - scipy >=1.0.0
    - transonic >=0.6.4

test:
  imports:
    - pylandstats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martibosch/pylandstats
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Computing landscape metrics in the Python ecosystem.
  description: |    
    Open-source Pythonic library to compute landscape metrics within the
    scientific Python stack (NumPy, pandas, geopandas, matplotlib...)
  doc_url: https://pylandstats.readthedocs.io/
  dev_url: https://github.com/martibosch/pylandstats

extra:
  recipe-maintainers:
    - martibosch
