{% set name = "pylandstats" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylandstats-{{ version }}.tar.gz
  sha256: cc7074949c4e0b52c90655443e4f9fd013aa679673661fe31475963bb7ab9b8b

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.9
    - setuptools >=74.1.0
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python >=3.9
    - dask-core
    - geopandas
    - matplotlib-base >=2.2
    - pandas >=0.23
    - rasterio >=1.0.0
    - scipy >=1.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pylandstats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martibosch/pylandstats
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Computing landscape metrics in the Python ecosystem.
  description: |    
    Open-source Pythonic library to compute landscape metrics in the Python
    ecosystem (NumPy, pandas, matplotlib...)
  doc_url: https://pylandstats.readthedocs.io
  dev_url: https://github.com/martibosch/pylandstats
  license: GPL-3.0-3.0.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martibosch
