{% set name = "pylandstats" %}
{% set version = "3.0.3" %}
{% set sha256 = "488ba70a550866b10af6b06805177d5a1f6c164c161cd33c3892f30e6a96270b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=40.8.0
    - wheel
    - transonic >=0.4.0
    - pythran  # [not win]
    - numba  # [win]
    - gast  # [not win]
  run:
    - python
    - numpy
    - pandas
    - geopandas
    - matplotlib-base
    - rasterio
    - scipy
    - transonic >=0.4.0
    - pythran  # [not win]
    - numba  # [win]
    - gast  # [not win]
test:
  imports:
    - pylandstats

about:
  home: https://github.com/martibosch/pylandstats
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Open-source Pythonic library to compute landscape metrics within the PyData stack (NumPy, pandas, matplotlib...)
  description: |
    Open-source Pythonic library to compute landscape metrics within the PyData
    stack (NumPy, pandas, matplotlib...)
  doc_url: https://pylandstats.readthedocs.io/
  dev_url: https://github.com/martibosch/pylandstats

extra:
  recipe-maintainers:
    - martibosch
