{% set name = "pylandstats" %}
{% set version = "1.1.1" %}
{% set sha256 = "b951c0399bb212f71cbec011f177bc4b2b9a214068a652d7c50620d7e874d20a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=40.8.0
    - wheel
    - pythran
  run:
    - python
    - numpy
    - pandas
    - geopandas
    - matplotlib
    - rasterio
    - scipy
    
test:
  imports:
    - pylandstats

about:
  home: https://github.com/martibosch/pylandstats
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: LICENSE
  summary: 'Open-source Pythonic library to compute landscape metrics within the PyData stack (NumPy, pandas, matplotlib...)'
  description: |
    Open-source Pythonic library to compute landscape metrics within the PyData
    stack (NumPy, pandas, matplotlib...)
  doc_url: https://pylandstats.readthedocs.io/
  dev_url: https://github.com/martibosch/pylandstats

extra:
  recipe-maintainers:
    - martibosch
