{% set name = "pylandstats" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylandstats-{{ version }}.tar.gz
  sha256: 488ba70a550866b10af6b06805177d5a1f6c164c161cd33c3892f30e6a96270b

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=74.1.0
    - wheel
    - cython
    - numpy >=2.0.0
    - pip
  run:
    - python
    - dask-core
    - geopandas
    - matplotlib-base >=2.2
    - pandas >=0.23
    - rasterio >=1.0.0
    - scipy >=1.0.0

test:
  imports:
    - pylandstats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martibosch/pylandstats
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Computing landscape metrics in the Python ecosystem.
  description: |    
    Open-source Pythonic library to compute landscape metrics in the Python
    ecosystem (NumPy, pandas, matplotlib...)
  doc_url: https://pylandstats.readthedocs.io
  dev_url: https://github.com/martibosch/pylandstats

extra:
  recipe-maintainers:
    - martibosch
