{% set name = "pylandstats" %}
{% set version = "2.0.0" %}
{% set sha256 = "1568a0e6ca78c7e840bbe481604fe96a3ce2c2f3242f25e78735e9b1850b9d87" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=40.8.0
    - wheel
    - transonic >=0.4.0
    - pythran  # [not win]
    - numba  # [win]
  run:
    - python
    - numpy
    - pandas
    - geopandas
    - matplotlib-base
    - rasterio
    - scipy
    - transonic >=0.4.0
    - pythran  # [not win]
    - numba  # [win]    
    
test:
  imports:
    - pylandstats

about:
  home: https://github.com/martibosch/pylandstats
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: LICENSE
  summary: 'Open-source Pythonic library to compute landscape metrics within the PyData stack (NumPy, pandas, matplotlib...)'
  description: |
    Open-source Pythonic library to compute landscape metrics within the PyData
    stack (NumPy, pandas, matplotlib...)
  doc_url: https://pylandstats.readthedocs.io/
  dev_url: https://github.com/martibosch/pylandstats

extra:
  recipe-maintainers:
    - martibosch
