travis:
  secure:
    BINSTAR_TOKEN: Usp3w6+mUMvWjsF/dvJVws0Vin5u2Fd2F7NPi6wn4j11WF7hUARLrJ5epP2MHnJ6neKZ1kKp1/p9OpJHoHUoJEkb2Glz/hGPU2yZXBrYcsl/VYt/B/DAry8lMxZ6Iu17ZXJwQwmipVIgyXv8gYKTEfYn4Cxz+NjNFTDbkIB7M274LpE5gtun+NeLrU+cA4kexZh4ia/jfh5ItMcvo8aGfxhacU9dPyAtiMJNzRMslKpcxOTpxgXbVj71Pin6xvjNzYjMMkceIyxFV7GAxB1/Sg0wRAta1p6pYXPl8+xDEFOiH8K/8bu3lp18dknzfCHd9P0MOypTBnSbTAoaUbEZFCeUVxouGkME7uJXrMAfcxuP6egfWiGCcPPjCV1A6ueCiswi+Po8Hq5PmRBdiJ/17dhULeRxgncwHVDttbgJCbK7l2QW1ujQsJqr+PNgWjA/XlQbuIoHghJZSeymRjPDmi/kt5fVmrEZed9HisFtKXg+zQAYDAlmtWIj6TWwgzAILqgWBBrBx2+kVFrQVAhbrvJ5McKw0KLWFYMk9UQZD0L2PQiCrSHzhAIzrAhxoUR2WT27jzQH5e5XIgqTRW3aniNJytphr0XrhPKF+4e3ZgIqL9d4HnA41lEYAzPpjfniEssAC+ewKTZYQ6iDq5g+89xWHtIHE8VNt9ilFBXgVrI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
