travis:
  secure:
    BINSTAR_TOKEN: wsaDheIo7Ul9EobkHjEa4f27zkjrIPZaEA8fdrh77ilYP2FNelVKz5YqQ13mgbgyqEySjRVnA+0wcCkZ3dGzYxps7zwqI2oT/qNg5ZlpCD4D6lhCDjMmBTpie+lds/N147NiBk90TPxKlTdU2bWEZbaEp0j5+c1X6Gv1cPceFfSmb3a1jqdMRy81xDdmnOZPJKm9R9gQdtEEVELTgQ8Ynx5OiNMaK3Z07Hf1AP8yJ+WWOldOxki3AVgFMtXU8lSfT4qMojxKQ+tfOa4gfZ8fi8h1eLHW1uzIhELHzD3Ty495bq4zaSxamHZ1EP5roMWZjAlp04iRdp/vGBZ5+ddSNChkMAoZhN2Jya7yBWa91phr60jWFr1KRiLzfVktTZQgdU+sYvpBlEMfyybhVOG+9jgkH3+2H+4ThFQPSoueY/9mtJ9EQ9cMTVghUnEv725Xdwc3YYj9v/biE4p3/LSs1TdvzSYyk69zV7CO8tNspt90MnmLgTF/ULo0EeFN9sAcsErEoeL98xOMH+aygwiZ/c0+Ta+L1Mo1lnhyXB4DnKPrWJHng48Tzu1PzxPAWdxyAZJsILUnjly4UmBKnV0j64nWV/VCNYq3i3WkkTCmgUTEdwjD9NKCPmfJbKaeTGdOdN53A6hicekxm14Xm8ws2W97l0/UUgdMdiIiltGhwHU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
